My first feature
App-Developer8866/hello_microverse_project pull request #1
Opened 2022-10-25 13:23 UTC by App-Developer8866

2022-10-25 15:22 UTC, anagudelogu requested changes
Hi @App-Developer8866, I'm Andres, your code reviewer!

Great job setting up your first project at Microverse! 🥂 🎆 
<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Great commit messages. 💯 
✅ Very professional and descriptive README file. 🗒️ 
✅ Perfect use of GitHub flow. 👍🏼 

## Required Changes ♻️
- [x] You did a great job installing the linters for GitHub 👍🏼. However, you also need to install them in your local environment to ensure consistent code format and a better way to identify errors at a local stage and not only by opening a pull request. 💯 Kindly refer to [this guide](https://github.com/microverseinc/linters-config/tree/master/html-css#set-up-linters-in-your-local-env) to install and configure them as required.
- [ ] I also noticed that your checks didn't run on your last commit. Since you have the correct GitHub configuration this could've happened due to the platform itself. 🐛  Please make sure that before you submit your project, all of your checks are passing. You can identify this expected behavior by checking the feedback provided by GitHub at the end of the pull request page: 🔧 

|Your output|Expected|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/197813492-f3957048-efdd-4aa9-9be2-54a2ad91bc0a.png)  | ![image](https://user-images.githubusercontent.com/77069011/197814485-abae27e2-961b-4395-978f-d7d9e30ac97e.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 15:22 UTC, anagudelogu commented on .gitignore
> +test.md
Great job ignoring the `test.md` file as required! 💯 However, remember to add the `node_modules` folder too. You can see this folder as a cache for all your project's external dependencies. It usually takes up a lot of space, so you wouldn't want to commit this to your remote repository 😨.  It can be recreated locally at any given time with your `package.json` and `package-lock.json`, so not having it in your repo doesn't represent a problem. 🔧

Kindly add it to your ignored files.  🤓

2022-10-25 15:22 UTC, anagudelogu commented on README.md
> +👤 **Author**
- [ ] **[OPTIONAL]:** You could change this Author handle to your actual name. This will let future readers know what your name is without having to navigate to a different page while also making it look more professional and attractive to possible recruiters! 💯 🤓

2022-10-25 15:58 UTC, App-Developer8866 commented
I have done all the required changes. What will now I do?


On Tue, Oct 25, 2022 at 8:22 PM Andres Agudelo Guzman <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @App-Developer8866 <https://github.com/App-Developer8866>, I'm Andres,
> your code reviewer!
>
> Great job setting up your first project at Microverse! 🥂 🎆
>
> <https://camo.githubusercontent.com/e8dc1cd1bdef105014a7bd95718fbdb4a3244d39d36f9dbf8c36a8822117757a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966>
>
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
> ✅ Great commit messages. 💯
> ✅ Very professional and descriptive README file. 🗒️
> ✅ Perfect use of GitHub flow. 👍🏼
> Required Changes ♻️
>
>    - You did a great job installing the linters for GitHub 👍🏼. However,
>    you also need to install them in your local environment to ensure
>    consistent code format and a better way to identify errors at a local stage
>    and not only by opening a pull request. 💯 Kindly refer to this guide
>    <https://github.com/microverseinc/linters-config/tree/master/html-css#set-up-linters-in-your-local-env>
>    to install and configure them as required.
>    - I also noticed that your checks didn't run on your last commit.
>    Since you have the correct GitHub configuration this could've happened due
>    to the platform itself. 🐛 Please make sure that before you submit
>    your project, all of your checks are passing. You can identify this
>    expected behavior by checking the feedback provided by GitHub at the end of
>    the pull request page: 🔧
>
> Your output Expected
> [image: image]
> <https://user-images.githubusercontent.com/77069011/197813492-f3957048-efdd-4aa9-9be2-54a2ad91bc0a.png> [image:
> image]
> <https://user-images.githubusercontent.com/77069011/197814485-abae27e2-961b-4395-978f-d7d9e30ac97e.png>
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In .gitignore
> <https://github.com/App-Developer8866/hello_microverse_project/pull/1#discussion_r1004583484>
> :
>
> > @@ -0,0 +1 @@
>
> +test.md
>
>
> Great job ignoring the test.md file as required! 💯 However, remember to
> add the node_modules folder too. You can see this folder as a cache for
> all your project's external dependencies. It usually takes up a lot of
> space, so you wouldn't want to commit this to your remote repository 😨.
> It can be recreated locally at any given time with your package.json and
> package-lock.json, so not having it in your repo doesn't represent a
> problem. 🔧
>
> Kindly add it to your ignored files. 🤓
> ------------------------------
>
> In README.md
> <https://github.com/App-Developer8866/hello_microverse_project/pull/1#discussion_r1004590545>
> :
>
> > +-Web Browser
>
> + -Code Editor:[visual Studio code](https://code.visualstudio.com/)
>
> +
>
> +### Setup
>
> +git clone https://github.com/App-Developer8866/hello_microverse_project
>
> +cd hello_microverse_project
>
> +~~~
>
> +Open a index.html file with your code editor of your choice and/or a browser of your choice.
>
> +~~~
>
> +Open the project using a live server extension that can be found into your code editor.
>
> +
>
> +
>
> +
>
> +## Authors
>
> +
>
> +👤 **Author**
>
>
>
>    - *[OPTIONAL]:* You could change this Author handle to your actual
>    name. This will let future readers know what your name is without having to
>    navigate to a different page while also making it look more professional
>    and attractive to possible recruiters! 💯 🤓
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/App-Developer8866/hello_microverse_project/pull/1#pullrequestreview-1154953163>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APCKTNCQSJBUETUMDCHQRI3WE73LXANCNFSM6AAAAAARN7A6ZE>
> .
> You are receiving this because you were mentioned.Message ID:
> <App-Developer8866/hello_microverse_project/pull/1/review/1154953163@
> github.com>
>

2022-10-25 16:00 UTC, App-Developer8866 commented on README.md
> +👤 **Author**
I have done all the required changes.

2022-10-26 07:27 UTC, jerryowusu approved these changes
Hi @App-Developer8866 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![chelsea-mason-approve](https://user-images.githubusercontent.com/65233860/197960429-a426ffd7-890d-41ea-9652-8d5cebd923c0.gif)


## Highlights
:white_check_mark: Great commit messages. :100:
:white_check_mark: Very professional and descriptive README file. :spiral_notepad:
:white_check_mark: Perfect use of GitHub flow. :+1: 


## Optional suggestions

- [ ] Kindly consider making PR summary, PR title, as well as branch names descriptive enough. Instead of `my first feature` or `my feature`, you can `Add linter files` `Create hello project` etc. This will help others know exactly what the project is about without  delving into your code

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 07:27 UTC, jerryowusu commented on README.md
> +- GitHub: [@githubhandle](https://github.com/App-Developer8866/)
[OPTIONAL] Kindly consider changing the `@githubhandle` to your github username, this will make your documentation look more proffessional and easy know who the author is.

2022-10-26 07:40 UTC, merged